---
- hosts: webservers
  remote_user: golpa
  tasks:
    - name: Install EPEL repo
      become: true
      package:
        name: epel-release
        state: latest
    - name: Install nginx
      become: true
      package: 
        name: nginx 
        state: latest
    - name: Starting nginx 
      become: true
      service: 
        name: nginx
        state: started
        masked: no